// <auto-generated />
using System;

using GraphQLDotNet.Api.Data.Context;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQLDotNet.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210107210134_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GraphQLDotNet.Api.Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2f7fba2-7894-4fa0-95a5-c577d669de10"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("3e85e4e3-d02a-4d52-ba80-83c34be6e233"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("20da5d43-94aa-490c-80fb-c9825ab46e28"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("81333fad-d25a-4c92-addf-886f4411d831"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("48edcb4d-57cf-4f81-85bb-ff066ab7ac0b"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("81333fad-d25a-4c92-addf-886f4411d831"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GraphQLDotNet.Api.Data.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e85e4e3-d02a-4d52-ba80-83c34be6e233"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("81333fad-d25a-4c92-addf-886f4411d831"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GraphQLDotNet.Api.Data.Entities.Account", b =>
                {
                    b.HasOne("GraphQLDotNet.Api.Data.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GraphQLDotNet.Api.Data.Entities.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
